### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by keanacobarde**
## Description
I added a PR template to the .github folder. 

## Related Issue
N/A

## Motivation and Context
#13 - 1/2, created a PR template NOT an Issue template. 

## How Can This Be Tested?
Attempt to create a PR and see if the template appears. 

## Screenshots (if appropriate):
N/A 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by GregM1992 — APPROVED** [review]
LGTM

**Comment by mshorecode** [comment]
+1

**Review by mshorecode — COMMENTED** [review]
LGTM + 1

**Review by mshorecode — APPROVED** [review]
LGTM +1

**Pull request merged**
